sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/saket_01 -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/saket_01 npm run test
