sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t saki0901/saket_01 -f Dockerfile.dev .

script:
  - docker run -e CI=true saki0901/saket_01 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "saket_01"
  env: "Saket01-env"
  bucket_name: "elasticbeanstalk-us-east-1-824729742367"
  bucket_path: "saket_01"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
